/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicio;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Chavez
 */
public class AbrirInventario extends javax.swing.JFrame {

    /**
     * Creates new form AbrirInventario
     */
    public AbrirInventario() {
        initComponents();
        agregarEventos();
        cargarInventario();
    }
    private void agregarEventos() {
        jMenuNuevo1.addActionListener(evt -> {
            NuevoProducto nuevoProducto = new NuevoProducto();
            nuevoProducto.setVisible(true);
            this.dispose();
        });

        jMenuSalir1.addActionListener(evt -> {
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Seguro que deseas regresar al Menú Principal?", "Salir",
                javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                Menu menuPrincipal = new Menu();
                menuPrincipal.setVisible(true);
                this.dispose();
            }
        });
    }
 
    private void cargarInventario() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        String query = "SELECT codigo_barras, nombre, categoria, cantidad, precio FROM productos";
        try (Connection conexion = conexionDB.conectar();
            PreparedStatement ps = conexion.prepareStatement(query);
            ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getString("codigo_barras");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("categoria");
                fila[3] = rs.getInt("cantidad");
                fila[4] = rs.getDouble("precio");
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los datos del inventario: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JMenuBar1 = new javax.swing.JMenuBar();
        JMenuPrincipal1 = new javax.swing.JMenu();
        jMenuNuevo1 = new javax.swing.JMenuItem();
        jMenuAbrir1 = new javax.swing.JMenuItem();
        jMenuSalir1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(417, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre", "Categoría", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        JMenuPrincipal1.setText("Principal");

        jMenuNuevo1.setText("Nuevo Producto");
        JMenuPrincipal1.add(jMenuNuevo1);

        jMenuAbrir1.setText("Abrir Inventario");
        JMenuPrincipal1.add(jMenuAbrir1);

        jMenuSalir1.setText("Ir al Menu");
        jMenuSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalir1ActionPerformed(evt);
            }
        });
        JMenuPrincipal1.add(jMenuSalir1);

        JMenuBar1.add(JMenuPrincipal1);

        setJMenuBar(JMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbrirInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AbrirInventario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar1;
    private javax.swing.JMenu JMenuPrincipal1;
    private javax.swing.JMenuItem jMenuAbrir1;
    private javax.swing.JMenuItem jMenuNuevo1;
    private javax.swing.JMenuItem jMenuSalir1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
